### PR TITLE
feat: add optional headers for JWKS client

### PR DESCRIPTION
**Pull request by vkuzbida-abacus**
Issue #, if available:
https://abacusinsights.atlassian.net/browse/INT-2727
Description of changes:
Add ability to pass request headers to JWKS Client
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by rsmayda — COMMENTED** [review]
Change looks good could you rebase your branch to latest so we can merge this in?

**Comment by vkuzbida-abacus** [comment]
@rsmayda sorry haven't seen your comment. Branch is updated now, could you please look to it again?

**Comment by carvantes** [comment]
Hi @vkuzbida-abacus , 

The change looks good. However, this change alone doesn't allow using custom headers since the `smartAuthorizationHelper.getJwksClient` function is only used internally.

Are you thinking on adding something like `jwksHeaders` to the `SMARTConfig`?
https://github.com/awslabs/fhir-works-on-aws-authz-smart/blob/782fe25b85254b451a252597a6fdbabd476f4342/src/smartConfig.ts#L117

Or is it just a small change since you are somehow using the `smartAuthorizationHelper` directly?

**Comment by vkuzbida-abacus** [comment]
Hey @carvantes !
We're using `getJwksClient` helper separately inside our custom implementation of Authorization class. But adding it to config makes sense to me.

**Comment by vkuzbida-abacus** [comment]
Hey @carvantes ! I've updated `SMARTConfig` and `getJwksClient` please take a look.

**Review by carvantes — DISMISSED** [review]

**Comment by carvantes** [comment]
@vkuzbida-abacus , the latest changes look good to me. I've approved them. However, we again have the "This branch is out-of-date with the base branch" issue. 
Please merge mainline into your branch and then I can merge this PR

**Comment by vkuzbida-abacus** [comment]
Thanks @carvantes ! I've rebased it one more time.

**Review by carvantes — APPROVED** [review]

**Pull request merged**
